platform: linux

image_resource:
  type: docker-image
  source:  
    repository: node
    tag: 10.13.0

inputs:
  - name: source-code
  - name: node_modules

run:
  path: source-code/ci/scripts/lint.sh