platform: linux

image_resource:
  type: docker-image
  source:  
    repository: python
    tag: 3-alpine

inputs:
  - name: source-code
  - name: node_modules

run:
  path: source-code/ci/scripts/static-analysis.sh