platform: linux

image_resource:
  type: docker-image
  source:  
    repository: mujib517/nodescan
    tag: latest

inputs:
  - name: source-code
  - name: node_modules

run:
  path: source-code/ci/scripts/static-analysis.sh