resources:
  - name: concourse-ci-node
    type: git
    source: 
      uri: https://github.com/Mujib517/concourse-ci-node
      branch: master

jobs:
  - name: build
    serial: true
    plan:
      - get: concourse-ci-node
        trigger: true

      - task: install-deps
        file: concourse-ci-node/ci/tasks/install-deps.yml
        input_mapping: 
          source-code: concourse-ci-node

      # - task: lint
      #   file: concourse-ci-node/ci/tasks/lint.yml
      #   input_mapping:
      #     source-code: concourse-ci-node

      # - task: unit-test
      #   file: concourse-ci-node/ci/tasks/unit-test.yml
      #   input_mapping:
      #       source-code: concourse-ci-node
          
      # - task: transpile
      #   file: concourse-ci-node/ci/tasks/transpile.yml
      #   input_mapping:
      #     source-code: concourse-ci-node